### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by MNDL-27** [shayaantx/jellyfin-tmdb-collections-plugin#1]
https://www.virustotal.com/gui/file/4c6001670d97be9a6b755c41ec59421a90047b87def93eb848703237dc544d11?nocache=1

![image](https://github.com/shayaantx/jellyfin-tmdb-collections-plugin/assets/96876555/13386f42-b452-498c-8adf-4e45d3956022)

**Comment by shayaantx** [comment]
@MNDL-27 weird I'm not using any libraries other than default stuff for jellyfin plugins, ill take a look

**Comment by shayaantx** [comment]
probably a false positive tbh, 

I rebuilt it with basically nothing, no dependencies, no files, and yet the TEHTRIS vendor keeps reporting it as generic malware? It doesn't even say what in the dll is triggering the "malware" label.

The only dependencies I use are 
```

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.7.*" />
    <PackageReference Include="Jellyfin.Model" Version="10.7.*" />
    <PackageReference Include="TMDbLib" Version="1.7.3-alpha" />
  </ItemGroup>
```

And none of those are malware, so at this point I'm not worried about it (also I built it on my pc and on a github action runner (which is what the releases run on) and it shows same false positive.

**Comment by MNDL-27** [comment]
> probably a false positive tbh,
> 
> I rebuilt it with basically nothing, no dependencies, no files, and yet the TEHTRIS vendor keeps reporting it as generic malware? It doesn't even say what in the dll is triggering the "malware" label.
> 
> The only dependencies I use are
> 
> ```
> 
>   <ItemGroup>
>     <PackageReference Include="Jellyfin.Controller" Version="10.7.*" />
>     <PackageReference Include="Jellyfin.Model" Version="10.7.*" />
>     <PackageReference Include="TMDbLib" Version="1.7.3-alpha" />
>   </ItemGroup>
> ```
> 
> And none of those are malware, so at this point I'm not worried about it (also I built it on my pc and on a github action runner (which is what the releases run on) and it shows same false positive.

no update on release section you u update that or you upload it on it virustotal to check it your self

**Comment by shayaantx** [comment]
> no update on release section you u update that or you upload it on it virustotal to check it your self

Huh? Are you asking for me to update release section with this information?

I uploaded a few to virustotal to check it myself

**Comment by MNDL-27** [comment]
ohh and it came out fine? Thats odd let me try again
